### PR TITLE
Add custom operator section

### PR DESCRIPTION
**Pull request by Weissnix4711**
[From docs.](https://typst.app/docs/reference/math/op/)

### CODE REVIEW

**Comment by johanvx** [comment]
Thanks for your contribution and sorry for being late!

This section is really great, but it seems to break the two-page layout of the document[^1]. Would you like to do some extra modification (no matter which part of the document) to keep the output PDF in 2 pages?

Another improvement for this PR is to adopt [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)[^2], for which the workflows (the one that makes releases indeed) are designed.

[^1]: I should have mentioned this in a CONTRIBUTING.md :flushed: 
[^2]: Again, I should have prepare a CONTRIBUTING.md...

**Comment by Weissnix4711** [comment]
> Thanks for your contribution and sorry for being late!

Absolutely no worries mate.

> * I should have mentioned this in a CONTRIBUTING.md 😳 [↩](#user-content-fnref-1-e88e8cdece0ee58454f4a339783d56ff)
> 
> * Again, I should have prepare a CONTRIBUTING.md... [↩](#user-content-fnref-2-e88e8cdece0ee58454f4a339783d56ff)

Honestly, I didn't even check for any contrib guidelines, so wouldn't have made a difference either way. I just threw this together in a min lol.

My local env seems a bit different from your ci, so I'll give gh actions a kick and see what it spits out. As for commit naming convention, lmk what to call it and ill squash everything. Otherwise, feel free to just rebase and reword yourself.

**Comment by johanvx** [comment]
The CI is intended to compile the PDF iff `undergradmath.typ` is modified.

As you can see [here](https://github.com/Weissnix4711/typst-undergradmath/actions/runs/6189381122), the output file is a 3-page document. This is because there's nearly no space for a new section in [release v1.0.0](https://github.com/johanvx/typst-undergradmath/releases/tag/v1.0.0). So I suggest to shrink other sections to free up some space for a new section and I'll do this by creating a PR to your `math-op` branch before merging this PR if you don't mind.

**Comment by johanvx** [comment]
I've made a fix commit to the `math-op` branch to keep the document in 2 pages and you can use `Sync fork` to update your `math-op` branch.

**Review by johanvx — APPROVED** [review]
Thanks again!

**Pull request merged**
